# Generated by Django 2.1.7 on 2019-04-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expend',
            name='people',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='income',
            name='people',
            field=models.CharField(max_length=8),
        ),
    ]
