# Generated by Django 2.1.7 on 2019-04-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountsystem', '0002_auto_20190426_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_password',
        ),
    ]
