# Generated by Django 2.1.7 on 2019-04-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsystem', '0003_remove_member_member_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expend',
            name='outcometype',
            field=models.CharField(choices=[('食品酒水', '食品酒水'), ('服饰', '服饰'), ('居家物业', '居家物业'), ('行车交通', '行车交通'), ('交流通讯', '交流通讯'), ('休闲娱乐', '休闲娱乐'), ('文化教育', '文化教育'), ('人情往来', '人情往来'), ('医疗医药', '医疗医药'), ('其他', '其他')], max_length=4),
        ),
    ]
